name: arcgis_yelp

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - python
  - requests
  - pip:
    - autodocsumm
    - azure-cosmos
    - azure-functions
    - build
    - bump2version
    - placekey
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
